### ISSUE TITLE
Why make a separate project when others are working on one together?

### ISSUE THREAD

**Issue by marcusjwhelan** [JamesMGreene/nestdb#25]
Myself and some other developers have already ported the project structure and abilities to a new project [TeDB](https://github.com/tedb-org/teDB). We are currently setting up a boilerplate for the storage driver so people can test their storage drivers before adding them. 

If you would like to join and help work on the project let me know. There are some things we are working on but overall it is still relatively fast. Would you be interested in working on that project?

**Comment by JamesMGreene** [comment]
@marcusjwhelan: Thanks for the offer but, no, I want to stick to an implementation that is still much more closely aligned with NeDB for now.
