### ISSUE TITLE
Unable to install nestdb using npm

### ISSUE THREAD

**Issue by Kaesebrot84** [JamesMGreene/nestdb#31]
Using
* `npm: 5.6.0`
* `node: 8.9.3`

if I run `npm install nestdb --save` I get;

> npm ERR! code E404
> npm ERR! 404 Not Found: nestdb@latest

And in the `xxx-debug.log`:

```
...
7 http fetch GET 404 https://registry.npmjs.org/nestdb 679ms
8 silly fetchPackageMetaData error for nestdb@latest 404 Not Found: nestdb@latest
9 verbose stack Error: 404 Not Found: nestdb@latest
...
```

So basically there is currently no **nestdb** on npm, am I right?

**Comment by daemonraco** [comment]
+1

**Comment by daemonraco** [comment]
well, this command seems to do the trick from now:
```
npm i -S git+https://github.com/JamesMGreene/nestdb.git
```

**Comment by Sieabah** [comment]
@JamesMGreene Can you just release the project on NPM?

**Comment by Sieabah** [comment]
I think it's safe to say this project was abandoned.

**Comment by Clearmist** [comment]
@JamesMGreene What's the status on publishing this project to NPM?

**Comment by Sieabah** [comment]
@Clearmist Probably would be easier to publish it yourself

**Comment by JamesMGreene** [comment]
Sorry for the delay, all. The project was definitely sidelined due to competing priorities on my time but I'm trying to get it back on track now!

`nestdb@2.0.0` was just published to NPM. :+1:

`nestdb@2.x` will maintain backward compatibility with `nedb@1.x` to allow for seamless transitions migrating from NeDB to NestDB. 👌

**Comment by JamesMGreene** [comment]
FWIW, I was trying to get to solving #6 before releasing it but clearly I've waited too long! Solving #6 is proving to be more time consuming than expected. :confused:
