### ISSUE TITLE
Permanently deleting an entry from persistant storage

### ISSUE THREAD

**Issue by soubhikchatterjee** [JamesMGreene/nestdb#47]
**Describe the bug**
I am using nestdb in one of my projects. It seems to be matching my needs so far. I see one issue though, when trying to delete a record, instead of deleting the entire record, it does a partial deletion. i.e. it deletes the record and adds $$deleted: true.

`{"$$deleted":true,"_id":"ZoXioqQSuosiMMFJ"}
`

Can the record be deleted permanently?
 
This is my code:
```
  db.remove({ name: doc.name }, {}, function (err, numRemoved) {
        // numRemoved = 1
      });
```
 

**Expected behavior**
The entry should be deleted completely.

**Screenshots**
https://share.getcloudapp.com/v1u4qWey

**Technical Specs:**
 - Platform Nodejs v14.4.0
 - Platform Version MacOS 10
 - Nest DB Version 2.0.0

**Comment by JamesMGreene** [comment]
This is intentional if you read through the documentation: https://github.com/JamesMGreene/nestdb#persistence

These records will be cleaned up the next time the database compacts (typically by running auto-compaction).
